# Generated by Django 5.1.4 on 2025-01-20 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_text', models.CharField(default='Default Banner Text', max_length=255)),
                ('banner_sub_text', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='images_uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_image', models.ImageField(blank=True, default='jpg', upload_to='image')),
                ('gallery_title', models.CharField(default='Armenia', max_length=100)),
                ('gallery_text', models.TextField()),
                ('gallery_price', models.IntegerField(default=0)),
            ],
        ),
    ]
