# Generated by Django 5.1.4 on 2025-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_banner',
            name='banner_image',
            field=models.ImageField(blank=True, default='svg', null=True, upload_to='images_uploaded'),
        ),
    ]
