# Generated by Django 5.1.4 on 2025-01-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0002_alter_travel_banner_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon_class', models.CharField(max_length=150)),
                ('services_title', models.CharField(max_length=200)),
                ('services_text', models.TextField()),
            ],
        ),
    ]
