# Generated by Django 5.1.4 on 2025-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0003_travel_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_packages_gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_image', models.ImageField(blank=True, default='jpg', upload_to='image')),
                ('gallery_title', models.CharField(default='Armenia', max_length=100)),
                ('gallery_text', models.TextField()),
            ],
        ),
    ]
