# Generated by Django 5.1.4 on 2025-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0004_travel_packages_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_image', models.ImageField(blank=True, default='jpg', upload_to='image')),
                ('review_fullname', models.CharField(max_length=30)),
                ('review_decr', models.CharField(max_length=200)),
                ('review_icons', models.CharField(max_length=50)),
            ],
        ),
    ]
