# Generated by Django 5.1.4 on 2025-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0006_travel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.TextField()),
                ('guest_num', models.IntegerField(default=0)),
                ('arrive_date', models.DateField()),
                ('leave_date', models.DateField()),
            ],
        ),
    ]
