# Generated by Django 5.1.4 on 2025-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=60)),
                ('people_num', models.IntegerField()),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TimeField()),
            ],
        ),
    ]
