# Generated by Django 5.1.4 on 2025-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_svg',
            field=models.FileField(default='svg', upload_to='svgs/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
